image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version
  tags:
    - ted

stages:
  - checks
  - test

lint:
  stage: checks
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

format:
  stage: checks
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit:
  stage: checks
  script:
    - cargo install cargo-audit
    - cargo audit

test:
  stage: test
  script:
    - cargo test
    # TODO: Fix issue with ted (gitlab runner) by modifying its config. See here for more details
    #  https://github.com/xd009642/tarpaulin/issues/146#issuecomment-554302029
    # - cargo install cargo-tarpaulin
    # - cargo tarpaulin --ignore-tests